### ISSUE TITLE
Status Effect background is not drawn in tooltips with custom icons

### ISSUE THREAD

**Issue by brandonandzeus** [brandonandzeus/Trainworks2#12]
Normally, the background indicates the type of status effect it is. Since this one is negative, there should be a red background behind the icon.

![Screenshot from 2023-12-06 20-40-21](https://github.com/brandonandzeus/Trainworks2/assets/101950394/a63e7f04-09ed-45c2-9635-5b265358c725)

**Comment by Lilker712** [comment]
More info about this Error that I found.
When there is a White Background in .png this bug doesn't exist **But** Then another shows up Bug.
With alpha channel
![WithApha](https://github.com/brandonandzeus/Trainworks2/assets/173284387/0adec927-52a3-4f06-981c-23e7e2208565)
Out of the alpha channel instead of White Background
![OutAlpha](https://github.com/brandonandzeus/Trainworks2/assets/173284387/42007ebd-92b3-47d8-b15e-4689f8f3d65a)
I hope that I help.

**Comment by brandonandzeus** [comment]
Thanks for the additional info.

In that case there's two Icons that can be provided.

```
        /// <summary>
        /// Path relative to the plugin's file path for the icon used in the Character Display UI.
        /// </summary>
        public string IconPath { get; set; }
        /// <summary>
        /// Path relative to the plugin's file path for the icon used for tooltips.
        /// Note the icon should be a black and white image sized 24x24.
        /// This is optional if IconPath and TooltipIconPath are the same.
        /// </summary>
        public string TooltipIconPath { get; set; }
```

So following from that IconPath should be a version with transparency and TooltipIconPath should be one with black and white.

Also if you are currently modding the game, I would recommend joining the MT Discord. The API is currently a work in progress. And it would be great to know what you are working on so I don't break your code as you are working on it!

**Comment by Lilker712** [comment]
Thanks for the info.
I am making a Mode that just adds a few more cards to the vanilla game. 
here is the link to the code: https://github.com/Lilker712/MonsterTrainMod.NewCards
And I joined the MT Discord thanks for the info. My username is "Lilker".
